### ISSUE TITLE
Entities do not take damage from Lava when sitting in any Boat variant made with Crimson and Warped wood that has sank below the surface of Lava.

### ISSUE THREAD

**Issue by LaGz4643** [Markus1002/Extra-Boats#66]
To reproduce, place any variant of Crimson or Warped Boat next to a pool of Lava, and either set your gamemode to Survival and ride the Boat into the Lava, or have an entity that is able to take fire damage enter the Boat and push it into the Lava. This happens because Boats cause riding entities to ignore collision with liquids to prevent them from being affected by the Water that normal Boats are usually floating in.

**Comment by bageldotjpg** [comment]
I will fix this (through some annoying mixin usage), but it is worth noting this is technically a Forge issue.
For some reason (I haven't deciphered, as I have not dug through it at all), if in a boat, being in lava extinguishes fire, while being in water does not. This is due to some change Forge made for custom fluids, but had some false logic. You can test this by placing signs in the same block as a boat, and then lava above those signs. If on fire, lava will put you out, and water will keep you on fire, while in the boat. May be worth getting some footage and screenshots and opening a report on Forge's github

**Comment by bageldotjpg** [comment]
Actually there's too many outlying issues for me to decided to fix this; you can track the Forge issue causing it here though: https://github.com/MinecraftForge/MinecraftForge/issues/9256
